### ISSUE TITLE
Good soft!  request more method in a action file~

### ISSUE THREAD

**Issue by w3yyb** [httpsoft/http-app#1]
**Description**  
 
Good soft! But a Action file only    one  handle action?

How I write more the one method in one actin file?

**Comment by devanych** [comment]
Yes. By design, this is the ADR (Action Domain Response) paradigm.

But if necessary, you can specify any PHP callable that returns `Psr\Http\Message\ResponseInterface`.

```php
$app->get('home', '/', HomeAction::class); // `HomeAction::handle()` will be used.
$app->get('about', '/about', [new AboutAction(), 'methodName']);
$app->get('contact', '/contact', fn ($request, $handler): ResponseInterface => /*...*/ );
```

See more details:
https://github.com/httpsoft/http-runner/blob/master/src/MiddlewareResolver.php
https://github.com/httpsoft/http-router/blob/master/src/Middleware/RouteDispatchMiddleware.php

Specifically using PHP callable:
https://github.com/httpsoft/http-runner/blob/master/src/MiddlewareResolver.php#L94

**Comment by w3yyb** [comment]
thank you very much.
